/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBatchesIndexRouteImport } from './routes/app.batches.index'
import { Route as AppBatchesBatchIdRouteImport } from './routes/app.batches.$batchId'
import { Route as AppBatchesBatchIdIndexRouteImport } from './routes/app.batches.$batchId.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesBatchIdRoute = AppBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesBatchIdIndexRoute = AppBatchesBatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBatchesBatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdRouteWithChildren
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/batches/$batchId/': typeof AppBatchesBatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppIndexRoute
  '/app/batches': typeof AppBatchesIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/': typeof AppIndexRoute
  '/app/batches/$batchId': typeof AppBatchesBatchIdRouteWithChildren
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/batches/$batchId/': typeof AppBatchesBatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/batches/$batchId'
    | '/app/batches/'
    | '/app/batches/$batchId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/app' | '/app/batches' | '/app/batches/$batchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/'
    | '/app/batches/$batchId'
    | '/app/batches/'
    | '/app/batches/$batchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/': {
      id: '/app/batches/'
      path: '/batches'
      fullPath: '/app/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$batchId': {
      id: '/app/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/app/batches/$batchId'
      preLoaderRoute: typeof AppBatchesBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$batchId/': {
      id: '/app/batches/$batchId/'
      path: '/'
      fullPath: '/app/batches/$batchId/'
      preLoaderRoute: typeof AppBatchesBatchIdIndexRouteImport
      parentRoute: typeof AppBatchesBatchIdRoute
    }
  }
}

interface AppBatchesBatchIdRouteChildren {
  AppBatchesBatchIdIndexRoute: typeof AppBatchesBatchIdIndexRoute
}

const AppBatchesBatchIdRouteChildren: AppBatchesBatchIdRouteChildren = {
  AppBatchesBatchIdIndexRoute: AppBatchesBatchIdIndexRoute,
}

const AppBatchesBatchIdRouteWithChildren =
  AppBatchesBatchIdRoute._addFileChildren(AppBatchesBatchIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBatchesBatchIdRoute: typeof AppBatchesBatchIdRouteWithChildren
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBatchesBatchIdRoute: AppBatchesBatchIdRouteWithChildren,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
